[package]
name = "tiny-game"
version = "0.1.0"
authors = ["memoryleak47 <memoryleak47@protonmail.ch>"]

[dependencies]
lazy_static = "1.0"
simdnoise = "2.3"
vulkano = "0.10"
vulkano-win = "0.10"
winit = "0.17"
